jdk:
- oraclejdk8
node_js:
 - node
notifications:
  email: false
install:
- npm --prefix src/main/ui install
script:
- npm --prefix src/main/ui run test
- npm --prefix src/main/ui run build:prod
- mvn verify
cache:
  directories:
  - $HOME/.m2
  - node_modules